openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-google-postgresql
components:
  schemas:
    variables:
      type: object
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          properties:
            vpc_id:
              description: |
                The ID of the VPC where the PostgreSQL service applies. It is
                a fully-qualified resource name, such as projects/{project_id}/global/networks/{network_id}. If not specified, a new VPC will be created.
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://cloud.google.com/sql/docs/db-versions.
          default: "15.0"
          enum:
          - "15.0"
          - "14.0"
          - "13.0"
          - "12.0"
          - "11.0"
          - "10.0"
          - "9.6"
          x-walrus-ui:
            group: Basic
            order: 5
        database:
          title: Database
          type: string
          description: |
            Specify the database name. The database name must be 1-60 characters long and start with any lower letter, combined with number, or symbols: - _.
            The database name cannot be PostgreSQL forbidden keyword.
          default: mydb
          x-walrus-ui:
            group: Basic
            order: 6
        username:
          title: Username
          type: string
          description: |
            Specify the account username. The username must be 1-32 characters long and start with lower letter, combined with number.
            The username cannot be PostgreSQL forbidden keyword.
          default: rdsuser
          x-walrus-ui:
            group: Basic
            order: 7
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 8-128 characters long and start with any letter, number, or symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 8
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
            The computing resource design of Google Cloud is very complex, it also needs to consider on the storage resource, please view the specification document for more information.

            Examples:
            ```
            resources:
              class: string, optional            # https://cloud.google.com/sql/docs/postgres/instance-settings
            ```
          default:
            class: db-f1-micro
          properties:
            class:
              default: db-f1-micro
              title: Class
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 9
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources, select from PD_SSD or PD_HDD.
            Choosing the storage resource is also related to the computing resource, please view the specification document for more information.

            Examples:
            ```
            storage:
              class: string, optional        # https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#disk_type
              size: number, optional         # in megabyte
            ```
          default:
            class: PD_SSD
            size: 10240
          properties:
            class:
              default: PD_SSD
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              default: 10240
              title: Size
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 10
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
